[package]
name = "cuda-nn-eval"
version = "0.1.0"
edition = "2018"

[dependencies]
cuda-sys = { path = "../cuda-sys" }
bytemuck = "1.7.0"
byteorder = "1.4.3"
itertools = "0.10.1"
prost = "0.8.0"
unwrap-match = "0.1.0"
cast_trait = "0.1.2"
rand = "0.8.4"
ndarray = "0.15.1"

[build-dependencies]
prost-build = "0.8.0"
