[package]
name = "alpha-zero"
description = "Implementation of AlphaZero, including selfplay game generation"
version = "0.2.0"
edition = "2018"

[features]
default = ["cuda", "onnxruntime"]
cuda = ["cuda-nn-eval"]

[dependencies]
board-game = { version = "0.3.6", path = "../../../board-game-rs" }

nn-graph = { path = "../nn-graph" }
cuda-nn-eval = { path = "../cuda-nn-eval", optional = true }

# TODO re-enable and implement these networks
#  (update their versions too)
#tch = { version = "0.4.1", optional = true }

onnxruntime = { version = "0.0.14", optional = true }

crossbeam = "0.8.1"
rayon = "1.5.1"
itertools = "0.10.1"
rand = "0.8.4"
ta = "0.5.0"
self_cell = "0.10.0"
rand_distr = "0.4.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
decorum = { version = "0.3.1", default-features = false, features = ["std"] }
internal-iterator = "0.1.2"
safe-transmute = "0.11.2"
image = { version = "0.23.14", default-features = false, features = ["png"] }
anyhow = "1.0.42"
lru = "0.6.6"
ndarray = "0.15.1"
ndarray-stats = "0.5.0"
unwrap-match = "0.1.0"
chess = "3.2.0"
flate2 = "1.0.22"
pgn-reader = "0.18.0"
tar = "0.4.37"
bzip2 = "0.4.3"
shakmaty = "0.19.0"
clap = "3.0.0-beta.5"